# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Automatic Upgrade from Omeka Classic to Omeka Semantic
email: daniel.github@berthereau.net
description: > # this means to ignore newlines until "baseurl:"
  "Upgrade from Omeka Classic to Omeka Semantic" is a simple plugin for Omeka 2
  that allows to upgrade automatically an installation to Omeka S (records,
  files,  config, themes and some plugins). For missing or new plugins or
  glitches in themes, or any other need on Omeka and digital libraries, contact
  me!
# baseurl: "/UpgradeToOmekaS"
# url: "https://daniel-km.github.com"
twitter_username:
github_username:  Daniel-KM

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
